# Generated by Django 3.2.16 on 2022-12-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('references', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Backendmodel',
            new_name='Projectmodel',
        ),
    ]
