# Generated by Django 3.2.16 on 2023-03-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221223_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencemodel',
            name='references',
        ),
    ]
